services:
  - type: web
    name: cattle-disease-diagnosis
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn cattle_diagnosis.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False