# Generated by Django 5.1.6 on 2025-05-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_diagnosishistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosishistory',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
