# Generated by Django 5.1.6 on 2025-05-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_diagnosishistory_confidence_score_delete_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosishistory',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
